### ISSUE TITLE
.DS_Store file is not ignored

### ISSUE THREAD

**Issue by omardieh** [devinfiachra/jcommerce#23]
![image](https://github.com/devinfiachra/jcommerce/assets/113672808/771d9cfe-3c82-4aba-a44d-52677a27bb48)

The .DS_Store file should not exist in the repository and it should be added to the .gitignore file, 
in case you are having issues ignoring it, please check the following stackoverflow post : 
https://stackoverflow.com/questions/18393498/gitignore-all-the-ds-store-files-in-every-folder-and-subfolder

**Comment by karenhernandeze** [comment]
Can I be assigned this one?
